//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_MUNTAKIM_BIN_HOSSAIN_P00194964
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public int aId { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<System.DateTime> openDate { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
